### ISSUE TITLE
Can not compile the folder

### ISSUE THREAD

**Issue by LottieWang** [ParAlg/GeoGraph#1]
Hi, when I run `sh compile.sh` from the project root directory, it failed because it can not cd to pybindings in line 23.  Besides, it also can not find the pybindings directory in line 29.  Can you carefully check the file path and the foldernames (some are pybinding and some are pybindings) and update the compile.sh?

**Comment by wangyiqiu** [comment]
Could you paste in the full error message, and let us know your platform and OS? Thank you.

**Comment by LottieWang** [comment]
`compile.sh: line 23: cd: pybindings: No such file or directory`
and 
`compile.sh: line 29: cd: pybindings: No such file or directory`
My OS is CentOS Linux 8

**Comment by wangyiqiu** [comment]
I pushed a few commits that should fix this problem. Previously, like you said there are some mistakes in the compilation script because it was out of sync with one of the submodules. Please pull the repository and let me know if the compilation still fails. Thank you.

**Comment by LottieWang** [comment]
It works now. Thank you.
